CREATE TABLE rally_cry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE defining_objective (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rally_cry_id BIGINT NOT NULL REFERENCES rally_cry(id),
    title VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE outcome (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    defining_objective_id BIGINT NOT NULL REFERENCES defining_objective(id),
    title VARCHAR(255) NOT NULL,
    description TEXT
);
